# Auto-generated by scripts/update-homebrew-formula.sh — do not edit manually.
# Regenerate with: ./scripts/update-homebrew-formula.sh v2.15.0 --push
class Zfb < Formula
  desc "Rust-built static-site engine — millisecond rebuilds, single binary"
  homepage "https://takazudomodular.com/pj/zudo-front-builder/"
  # Source: GitHub Releases from Takazudo/zudo-front-builder (not the npm registry).
  # Archive contract: zfb-{semver}-{target-triple}.tar.gz, one file at archive root.
  license "MIT"
  version "2.15.0"

  on_macos do
    on_arm do
      url "https://github.com/Takazudo/zudo-front-builder/releases/download/v2.15.0/zfb-2.15.0-aarch64-apple-darwin.tar.gz"
      sha256 "37f259ccad06291b37b45d08456f5d1ba4aa0573eb1e16ef834d66a270b72e07"
    end

    on_intel do
      url "https://github.com/Takazudo/zudo-front-builder/releases/download/v2.15.0/zfb-2.15.0-x86_64-apple-darwin.tar.gz"
      sha256 "d2be00b0dd80fd7c4b9c72bfdfdec6b30968bf0a2cbf7ffd23cd3fdb7c6ffe41"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Takazudo/zudo-front-builder/releases/download/v2.15.0/zfb-2.15.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "9980190b6dc2a78a8cc24d57c27f6a47b99f0782742b8050fab3f443b95f2f91"
    end

    on_intel do
      url "https://github.com/Takazudo/zudo-front-builder/releases/download/v2.15.0/zfb-2.15.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "71d4cfefce4e906cab953c64f2df08191d4277b65561286421b0788ea940ba9b"
    end
  end

  def install
    bin.install "zfb"
  end

  test do
    system bin/"zfb", "--version"
  end
end
