# Auto-generated by scripts/update-homebrew-formula.sh — do not edit manually.
# Regenerate with: ./scripts/update-homebrew-formula.sh v1.0.0 --push
class Zfb < Formula
  desc "Rust-built static-site engine — millisecond rebuilds, single binary"
  homepage "https://takazudomodular.com/pj/zudo-front-builder/"
  # Source: GitHub Releases from Takazudo/zudo-front-builder (not the npm registry).
  # Archive contract: zfb-{semver}-{target-triple}.tar.gz, one file at archive root.
  license "MIT"
  version "1.0.0"

  on_macos do
    on_arm do
      url "https://github.com/Takazudo/zudo-front-builder/releases/download/v1.0.0/zfb-1.0.0-aarch64-apple-darwin.tar.gz"
      sha256 "d4bf28817db44ac04803f28eb93ed003384f0ee34e1d51ae0620b4cc628aef7f"
    end

    on_intel do
      url "https://github.com/Takazudo/zudo-front-builder/releases/download/v1.0.0/zfb-1.0.0-x86_64-apple-darwin.tar.gz"
      sha256 "a5d14c6d94aa906292004e2c3371322e935e018b3c913bc0c215f0802f50a5ef"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Takazudo/zudo-front-builder/releases/download/v1.0.0/zfb-1.0.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "6afa2f745854057e9a65b4e7972911de23c265cc91fd888d29b5846a38b86a34"
    end

    on_intel do
      url "https://github.com/Takazudo/zudo-front-builder/releases/download/v1.0.0/zfb-1.0.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "66404b7c2a138dfb21a81e277b9b6dbb996988d2f5c75571832190198495b374"
    end
  end

  def install
    bin.install "zfb"
  end

  test do
    system bin/"zfb", "--version"
  end
end
