# Auto-generated by scripts/update-homebrew-formula.sh — do not edit manually.
# Regenerate with: ./scripts/update-homebrew-formula.sh v2.4.0 --push
class Zfb < Formula
  desc "Rust-built static-site engine — millisecond rebuilds, single binary"
  homepage "https://takazudomodular.com/pj/zudo-front-builder/"
  # Source: GitHub Releases from Takazudo/zudo-front-builder (not the npm registry).
  # Archive contract: zfb-{semver}-{target-triple}.tar.gz, one file at archive root.
  license "MIT"
  version "2.4.0"

  on_macos do
    on_arm do
      url "https://github.com/Takazudo/zudo-front-builder/releases/download/v2.4.0/zfb-2.4.0-aarch64-apple-darwin.tar.gz"
      sha256 "1d458dc272826b594233204bd35e1ccd2a4ee50917fc20cbe3cadead947ad58b"
    end

    on_intel do
      url "https://github.com/Takazudo/zudo-front-builder/releases/download/v2.4.0/zfb-2.4.0-x86_64-apple-darwin.tar.gz"
      sha256 "f019dc9a741e973db9b3a9656aa1a51b729f6934b2b56af51c6fbd73acc20468"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Takazudo/zudo-front-builder/releases/download/v2.4.0/zfb-2.4.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "bd78a7ffe33042bdd65521cf094004de4e2c36f03b0e984957528551128381e2"
    end

    on_intel do
      url "https://github.com/Takazudo/zudo-front-builder/releases/download/v2.4.0/zfb-2.4.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a5d0f648696d65eb80d80b4caef7c68d1718d849ed39c6163ac002953817d63c"
    end
  end

  def install
    bin.install "zfb"
  end

  test do
    system bin/"zfb", "--version"
  end
end
